create table if not exists public.mercadolibre_oauth_sessions (
  id uuid primary key default gen_random_uuid(),
  admin_user_id uuid not null references public.admin_users(id) on delete cascade,
  state_hash text not null unique,
  code_verifier text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_mercadolibre_oauth_sessions_expires
  on public.mercadolibre_oauth_sessions (expires_at);

alter table public.mercadolibre_oauth_sessions enable row level security;
revoke all on public.mercadolibre_oauth_sessions from anon, authenticated;

create table if not exists public.mercadolibre_connection (
  id smallint primary key default 1 check (id = 1),
  user_id bigint,
  site_id text,
  nickname text,
  token_type text,
  scope text,
  access_secret_id uuid,
  refresh_secret_id uuid,
  expires_at timestamptz,
  connected_at timestamptz,
  last_refresh_at timestamptz,
  updated_at timestamptz not null default now(),
  status text not null default 'disconnected'
    check (status in ('disconnected','connected','error')),
  last_error text
);

alter table public.mercadolibre_connection enable row level security;
revoke all on public.mercadolibre_connection from anon, authenticated;

create table if not exists public.mercadolibre_webhook_events (
  id bigint generated by default as identity primary key,
  dedup_key text not null unique,
  topic text,
  resource text,
  user_id bigint,
  application_id bigint,
  attempts integer,
  sent_at timestamptz,
  received_at timestamptz not null default now(),
  verified_at timestamptz,
  verification_status integer,
  processed_at timestamptz,
  error text
);

create index if not exists idx_mercadolibre_webhook_events_pending
  on public.mercadolibre_webhook_events (processed_at, received_at desc);

alter table public.mercadolibre_webhook_events enable row level security;
revoke all on public.mercadolibre_webhook_events from anon, authenticated;

create or replace function public.mercadolibre_store_tokens(
  p_access_token text,
  p_refresh_token text,
  p_user_id bigint,
  p_site_id text,
  p_nickname text,
  p_token_type text,
  p_scope text,
  p_expires_in integer
)
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_access_id uuid;
  v_refresh_id uuid;
  v_now timestamptz := now();
begin
  if coalesce(length(p_access_token),0) < 10 then
    raise exception 'invalid access token';
  end if;

  select access_secret_id, refresh_secret_id
    into v_access_id, v_refresh_id
  from public.mercadolibre_connection
  where id = 1
  for update;

  if v_access_id is null then
    select id into v_access_id
    from vault.decrypted_secrets
    where name = 'cardnest_mercadolibre_access_token'
    limit 1;
  end if;

  if v_access_id is null then
    v_access_id := vault.create_secret(
      p_access_token,
      'cardnest_mercadolibre_access_token',
      'CardNest Mercado Libre access token'
    );
  else
    perform vault.update_secret(v_access_id, p_access_token);
  end if;

  if coalesce(length(p_refresh_token),0) >= 10 then
    if v_refresh_id is null then
      select id into v_refresh_id
      from vault.decrypted_secrets
      where name = 'cardnest_mercadolibre_refresh_token'
      limit 1;
    end if;

    if v_refresh_id is null then
      v_refresh_id := vault.create_secret(
        p_refresh_token,
        'cardnest_mercadolibre_refresh_token',
        'CardNest Mercado Libre refresh token'
      );
    else
      perform vault.update_secret(v_refresh_id, p_refresh_token);
    end if;
  end if;

  insert into public.mercadolibre_connection (
    id,user_id,site_id,nickname,token_type,scope,
    access_secret_id,refresh_secret_id,expires_at,
    connected_at,last_refresh_at,updated_at,status,last_error
  )
  values (
    1,p_user_id,p_site_id,p_nickname,p_token_type,p_scope,
    v_access_id,v_refresh_id,v_now + make_interval(secs => greatest(coalesce(p_expires_in,0),60)),
    v_now,v_now,v_now,'connected',null
  )
  on conflict (id) do update set
    user_id = excluded.user_id,
    site_id = excluded.site_id,
    nickname = excluded.nickname,
    token_type = excluded.token_type,
    scope = excluded.scope,
    access_secret_id = excluded.access_secret_id,
    refresh_secret_id = coalesce(excluded.refresh_secret_id, public.mercadolibre_connection.refresh_secret_id),
    expires_at = excluded.expires_at,
    connected_at = coalesce(public.mercadolibre_connection.connected_at, excluded.connected_at),
    last_refresh_at = excluded.last_refresh_at,
    updated_at = excluded.updated_at,
    status = 'connected',
    last_error = null;
end;
$$;

revoke all on function public.mercadolibre_store_tokens(text,text,bigint,text,text,text,text,integer) from public, anon, authenticated;
grant execute on function public.mercadolibre_store_tokens(text,text,bigint,text,text,text,text,integer) to service_role;

create or replace function public.mercadolibre_get_tokens()
returns table (
  access_token text,
  refresh_token text,
  expires_at timestamptz,
  user_id bigint,
  site_id text,
  nickname text,
  scope text,
  status text
)
language sql
security definer
set search_path = public, vault, pg_temp
as $$
  select
    a.decrypted_secret,
    r.decrypted_secret,
    c.expires_at,
    c.user_id,
    c.site_id,
    c.nickname,
    c.scope,
    c.status
  from public.mercadolibre_connection c
  left join vault.decrypted_secrets a on a.id = c.access_secret_id
  left join vault.decrypted_secrets r on r.id = c.refresh_secret_id
  where c.id = 1
  limit 1;
$$;

revoke all on function public.mercadolibre_get_tokens() from public, anon, authenticated;
grant execute on function public.mercadolibre_get_tokens() to service_role;

create or replace function public.mercadolibre_disconnect()
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_access_id uuid;
  v_refresh_id uuid;
begin
  select access_secret_id, refresh_secret_id
    into v_access_id, v_refresh_id
  from public.mercadolibre_connection
  where id = 1
  for update;

  if v_access_id is not null then
    delete from vault.secrets where id = v_access_id;
  end if;
  if v_refresh_id is not null then
    delete from vault.secrets where id = v_refresh_id;
  end if;

  insert into public.mercadolibre_connection (id,status,updated_at)
  values (1,'disconnected',now())
  on conflict (id) do update set
    user_id = null,
    site_id = null,
    nickname = null,
    token_type = null,
    scope = null,
    access_secret_id = null,
    refresh_secret_id = null,
    expires_at = null,
    connected_at = null,
    last_refresh_at = null,
    updated_at = now(),
    status = 'disconnected',
    last_error = null;
end;
$$;

revoke all on function public.mercadolibre_disconnect() from public, anon, authenticated;
grant execute on function public.mercadolibre_disconnect() to service_role;
